# Generated by Django 5.2.7 on 2025-10-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pago', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (ejemplo: 10.00 = 10%)', max_digits=5, verbose_name='Descuento (%)')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio de promoción')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin de promoción')),
                ('imagen_promocion', models.ImageField(blank=True, default='promociones_imagenes/default.png', null=True, upload_to='promociones_imagenes/', verbose_name='Imagen de promoción')),
                ('categorias', models.ManyToManyField(blank=True, related_name='promociones', to='producto.categoria', verbose_name='Categorías aplicadas')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='pago.metodopago', verbose_name='Método de pago')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='producto.producto', verbose_name='Productos aplicados')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
