# Generated by Django 5.2.7 on 2025-10-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_usuario_departamento_usuario_pais_usuario_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPerfilTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='tienda/default.png', upload_to='tienda/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es principal?')),
            ],
            options={
                'verbose_name': 'Imagen de tienda',
                'verbose_name_plural': 'Imágenes de tiendas',
                'ordering': ['-es_principal', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=150, verbose_name='Nombre de la tienda')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('codigo_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='usuario.codigopais', verbose_name='Código del país')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='usuario.departamento', verbose_name='Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='usuario.distrito', verbose_name='Distrito')),
                ('imagenes', models.ManyToManyField(blank=True, related_name='tiendas', to='tienda.imagenperfiltienda', verbose_name='Imágenes')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='usuario.pais', verbose_name='País')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='usuario.provincia', verbose_name='Provincia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to='usuario.usuario', verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['nombre_tienda'],
                'constraints': [models.UniqueConstraint(fields=('usuario',), name='unique_usuario_tienda')],
            },
        ),
    ]
