# Generated by Django 5.2.7 on 2025-10-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_ca', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('imagen_categoria', models.ImageField(blank=True, default='categorias_imagenes/default_categoria.png', null=True, upload_to='categorias_imagenes/', verbose_name='Imagen de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nomb_ca'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_marca', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la marca')),
                ('imagen_marca', models.ImageField(blank=True, default='marcas_imagenes/default_marca.png', null=True, upload_to='marcas_imagenes/', verbose_name='Imagen de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nomb_marca'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_prod', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (S/.)')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('preventa', 'Preventa'), ('reacondicionado', 'Reacondicionado'), ('descargable', 'Descargable')], max_length=20, verbose_name='Estado')),
                ('categoria', models.ManyToManyField(related_name='productos', to='producto.categoria', verbose_name='Categorías')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='producto.marca', verbose_name='Marca')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='productos_imagenes/default_producto.png', upload_to='productos_imagenes/', verbose_name='Imagen del producto')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es principal?')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='producto.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
