# Generated by Django 5.2.7 on 2025-10-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('usuario', '0002_usuario_departamento_usuario_pais_usuario_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (S/.)')),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de entrega')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('estado', models.CharField(choices=[('pendiente_envio', 'Pendiente de Envío'), ('preparando_envio', 'Preparando Envío'), ('en_transito', 'En Tránsito'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_envio', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='carrito.carrito', verbose_name='Carrito asociado')),
                ('distrito_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='usuario.distrito', verbose_name='Distrito')),
                ('pais_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='usuario.pais', verbose_name='País')),
                ('provincia_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='usuario.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
