# Generated by Django 5.2.7 on 2025-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
