# Generated by Django 5.2.7 on 2025-10-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_orden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_meto', models.CharField(max_length=50, unique=True, verbose_name='Nombre del método')),
                ('imagen_metodo', models.ImageField(blank=True, default='metodos_pago_imagenes/default.png', null=True, upload_to='metodos_pago_imagenes/', verbose_name='Imagen del método')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nomb_meto'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto pagado (S/.)')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pago.metodopago', verbose_name='Método de pago')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='detalle_orden.orden', verbose_name='Orden asociada')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
