# Generated by Django 5.2.7 on 2025-10-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='pago',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de transacción (referencia externa)'),
        ),
    ]
