# Generated by Django 5.2.7 on 2025-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_pago_actualizado_en_pago_notas_pago_transaccion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
